
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otqllxpscbiugpfhbbbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cWxseHBzY2JpdWdwZmhiYmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjQ2MzQsImV4cCI6MjA2MTQwMDYzNH0.5nASOn_B_rIYuSgRGqetswdlKnbwhNew9f8r23FMsRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
